export const EVENT_POSTERS = [
  // ── FIRST 4: AUTHENTIC LIVE PERFORMANCE VIDEOS (R2 Streaming) ──
  {
    id: 'house-party',
    category: 'House Party & Acoustic',
    tab: '🎬 House Party',
    tag: '🔥 #1 HOUSE PARTY VIDEO',
    title: 'Private House Party Acoustic Singer',
    subtitle: 'Soulful Bollywood, Pop & Unplugged Vocalists with Compact Sound Setup for Living Rooms',
    poster: '/posters/house_party_acoustic.jpg',
    videoUrl: 'https://pub-1802bb19214743ffa99aa227f25e7ede.r2.dev/heroSec/HerSec%20Videos/house%20party%20Landscape.mp4',
    videoTitle: 'Private House Party Acoustic Performance',
    mediaType: 'video',
    regularPrice: '₹16,000',
    offerPrice: '₹6,999',
    discount: '55%–65% OFF',
    rating: '4.96★ (1,450+ Parties)'
  },
  {
    id: 'birthday-party',
    category: 'Birthday Celebrations',
    tab: '🎬 Birthday Bash',
    tag: '🎉 BIRTHDAY SPECIAL VIDEO',
    title: 'Birthday House Party Singer & Live Guitarist',
    subtitle: 'High-Energy Bollywood Medleys, Retro Classics & Singalongs with Portable Sound',
    poster: '/posters/birthday_party_singer.jpg',
    videoUrl: 'https://pub-1802bb19214743ffa99aa227f25e7ede.r2.dev/heroSec/HerSec%20Videos/Birthday%20Party%20Landscape.mp4',
    videoTitle: 'Birthday House Party Live Performance',
    mediaType: 'video',
    regularPrice: '₹15,000',
    offerPrice: '₹6,499',
    discount: 'Flat 57% OFF',
    rating: '4.98★ (2,100+ Birthdays)'
  },
  {
    id: 'farmhouse-cocktail',
    category: 'Farmhouse & Cocktails',
    tab: '🎬 Farmhouse Party',
    tag: '🌴 LUXURY LAWN VIDEO',
    title: 'Farmhouse Lawn Cocktail Party Singer',
    subtitle: 'Bollywood Acoustic Singer & Saxophone Duo for Poolside & Lawn Gatherings',
    poster: '/posters/farmhouse_cocktail_party.jpg',
    videoUrl: 'https://pub-1802bb19214743ffa99aa227f25e7ede.r2.dev/heroSec/HerSec%20Videos/farm%20house%20Portrait.mp4',
    videoTitle: 'Farmhouse Live Acoustic Gathering',
    mediaType: 'video',
    regularPrice: '₹32,000',
    offerPrice: '₹13,999',
    discount: 'Flat 56% OFF',
    rating: '4.97★ (520+ Farmhouses)'
  },
  {
    id: 'bhajan-bhakti',
    category: 'Devotional & Bhajan',
    tab: '🎬 Bhajan Sandhya',
    tag: '🙏 SPIRITUAL CONCERT VIDEO',
    title: 'Bhakti Sangeet & Bhajan Sandhya at Home',
    subtitle: 'Soulful Krishna, Mata Ki Chowki & Kirtan Vocalists with Dholak & Flute for Home Poojas',
    poster: '/posters/bhajan_bhakti_concert.jpg',
    videoUrl: 'https://pub-1802bb19214743ffa99aa227f25e7ede.r2.dev/heroSec/HerSec%20Videos/Book%20a%20Bhajan%20concert%20at%20home%20Portrait.mp4',
    videoTitle: 'Home Bhajan Sandhya Live Concert',
    mediaType: 'video',
    regularPrice: '₹16,000',
    offerPrice: '₹6,999',
    discount: 'Flat 56% OFF',
    rating: '5.0★ (620+ Poojas)'
  },

  // ── NEXT 6: CURATED ARTIST POSTER CARDS (High-Resolution Images) ──
  {
    id: 'terrace-sundowner',
    category: 'Terrace & Sundowner',
    tab: '🌆 Terrace Jam',
    tag: '🌅 SUNSET SPECIAL',
    title: 'Rooftop Terrace Sundowner Jam',
    subtitle: 'Acoustic Guitarist & Bongo Percussionist for Open-Air Golden Hour & Sunset Vibes',
    poster: '/posters/terrace_sundowner_jam.jpg',
    videoUrl: null,
    videoTitle: null,
    mediaType: 'image',
    regularPrice: '₹20,000',
    offerPrice: '₹8,499',
    discount: 'Flat 58% OFF',
    rating: '4.94★ (680+ Rooftops)'
  },
  {
    id: 'bollywood-unplugged',
    category: 'Bollywood & Unplugged',
    tab: '🎸 Bollywood Unplugged',
    tag: '✨ 100% LIVE RETRO & POP',
    title: 'Bollywood Unplugged & Evergreen Hits',
    subtitle: 'Soulful Kishore Kumar, Arijit Singh & 90s Classics for Cozy Living Rooms & Terrace Evenings',
    poster: '/posters/house_party_acoustic.jpg',
    videoUrl: null,
    videoTitle: null,
    mediaType: 'image',
    regularPrice: '₹18,000',
    offerPrice: '₹7,499',
    discount: 'Flat 58% OFF',
    rating: '4.98★ (1,600+ Parties)'
  },
  {
    id: 'ghazal-sufi',
    category: 'Ghazal & Sufi',
    tab: '🌙 Sufi & Ghazal',
    tag: '🕯️ ROMANTIC MEHFIL',
    title: 'Intimate Ghazal & Sufi Mehfil',
    subtitle: 'Live Harmonium, Acoustic Tabla & Classical Vocalist for Candlelight Dinners & Anniversaries',
    poster: '/posters/ghazal_sufi_night.jpg',
    videoUrl: null,
    videoTitle: null,
    mediaType: 'image',
    regularPrice: '₹24,000',
    offerPrice: '₹9,999',
    discount: 'Flat 58% OFF',
    rating: '5.0★ (740+ Anniversaries)'
  },
  {
    id: 'anniversary-dinner',
    category: 'Anniversary & Romantic',
    tab: '💖 Romantic Mehfil',
    tag: '💍 ANNIVERSARY SPECIAL',
    title: 'Anniversary & Romantic Dinner Acoustic Singer',
    subtitle: 'Soft Candlelight Bollywood Ballads, Guitar & Soulful Vocals for Intimate Couple Gatherings',
    poster: '/posters/ghazal_sufi_night.jpg',
    videoUrl: null,
    videoTitle: null,
    mediaType: 'image',
    regularPrice: '₹19,000',
    offerPrice: '₹7,999',
    discount: 'Flat 58% OFF',
    rating: '5.0★ (850+ Anniversaries)'
  },
  {
    id: 'wedding-band',
    category: 'Wedding & Sangeet',
    tab: '👑 Wedding Sangeet',
    tag: '👑 ROYAL SANGEET SPECIAL',
    title: 'Grand Sangeet & Royal Live Singers',
    subtitle: 'High-Octane 4 to 6 Piece Live Troupe, Sufi Rock & Bollywood Anthems with Sound System',
    poster: '/posters/wedding_sangeet_band.jpg',
    videoUrl: null,
    videoTitle: null,
    mediaType: 'image',
    regularPrice: '₹65,000',
    offerPrice: '₹28,999',
    discount: 'Up to 60% OFF',
    rating: '4.98★ (850+ Weddings)'
  },
  {
    id: 'haldi-mehendi',
    category: 'Haldi & Mehendi',
    tab: '🌼 Haldi & Mehendi',
    tag: '💛 WEDDING FESTIVITIES',
    title: 'Haldi & Mehendi Folk & Dholak Troupe',
    subtitle: 'Upbeat Punjabi Wedding Folk, Dholak & Traditional Tappe Singalongs for Home Functions',
    poster: '/posters/haldi_mehendi_celebration.jpg',
    videoUrl: null,
    videoTitle: null,
    mediaType: 'image',
    regularPrice: '₹18,000',
    offerPrice: '₹7,499',
    discount: 'Flat 58% OFF',
    rating: '4.95★ (1,100+ Functions)'
  }
];

export const FEATURED_IMAGE_CARDS = [
  {
    id: 'hp-acoustic',
    category: 'HOUSE PARTY ACOUSTIC',
    title: 'Private House Party Acoustic Singer',
    subtitle: 'Guitarist & Soulful Vocalist with Compact Sound Setup',
    price: '₹6,999',
    regularPrice: '₹14,999',
    discount: 'Flat 53% OFF',
    tag: '⚡ Best for Living Rooms',
    rating: '4.9★',
    badge: '100% Acoustic Verified',
    image: '/posters/house_party_acoustic.jpg',
  },
  {
    id: 'wedding-sangeet',
    category: 'WEDDING & SANGEET',
    title: 'Grand Sangeet & Royal Live Bands',
    subtitle: 'High-Energy Bollywood 4-5 Piece Live Wedding Ensemble',
    price: '₹28,999',
    regularPrice: '₹55,000',
    discount: 'Flat 47% OFF',
    tag: '👑 Royal Celebrations',
    rating: '5.0★',
    badge: 'Stage Sound Included',
    image: '/posters/wedding_sangeet_band.jpg',
  },
  {
    id: 'terrace-jam',
    category: 'TERRACE & SUNDOWNER',
    title: 'Rooftop Terrace Sundowner Jam',
    subtitle: 'Golden Hour Indie & Bollywood Pop Singalong Vibe',
    price: '₹8,499',
    regularPrice: '₹18,000',
    discount: 'Flat 52% OFF',
    tag: '🌅 Sunset Favourite',
    rating: '4.95★',
    badge: 'Warm Mood Lighting Ready',
    image: '/posters/terrace_sundowner_jam.jpg',
  },
  {
    id: 'birthday-singer',
    category: 'BIRTHDAY CELEBRATIONS',
    title: 'Birthday Party Singer & Live Guitarist',
    subtitle: 'High-Energy Bollywood Medleys & Singalongs with Sound Setup',
    price: '₹6,499',
    regularPrice: '₹15,000',
    discount: 'Flat 57% OFF',
    tag: '🎂 Birthday Special',
    rating: '4.98★',
    badge: 'Mic & Acoustic Gear Included',
    image: '/posters/birthday_party_singer.jpg',
  },
  {
    id: 'ghazal-sufi',
    category: 'SUFI & GHAZAL',
    title: 'Intimate Ghazal & Sufi Mehfil',
    subtitle: 'Harmonium, Acoustic Tabla & Classical Vocalist for Anniversaries',
    price: '₹9,999',
    regularPrice: '₹24,000',
    discount: 'Flat 53% OFF',
    tag: '♥ Romantic Mehfil',
    rating: '5.0★',
    badge: 'Harmonium & Live Tabla',
    image: '/posters/ghazal_sufi_night.jpg',
  },
];
