export const EVENT_POSTERS = [
  {
    id: 'house-party',
    category: 'House Party & Acoustic',
    tab: '🎤 House Party',
    tag: '🔥 #1 FOR HOUSE PARTIES',
    title: 'Private House Party Acoustic Singer',
    subtitle: 'Soulful Bollywood, Pop & Unplugged Vocalists with Compact Sound Setup for Living Rooms',
    poster: '/posters/house_party_acoustic.jpg',
    videoUrl: 'https://pub-1802bb19214743ffa99aa227f25e7ede.r2.dev/heroSec/HerSec%20Videos/house%20party%20Landscape.mp4',
    videoTitle: 'Live House Party Singer Performance',
    regularPrice: '₹16,000',
    offerPrice: '₹6,999',
    discount: '55%–65% OFF',
    slots: '3 Slots Left Today',
    rating: '4.96★ (1,450+ Parties)'
  },
  {
    id: 'terrace-sundowner',
    category: 'Terrace & Sundowner',
    tab: '🌆 Terrace Jam',
    tag: '🌅 SUNSET SPECIAL',
    title: 'Rooftop Terrace Sundowner Jam',
    subtitle: 'Acoustic Guitarist & Bongo Percussionist for Open-Air Golden Hour & Sunset Vibes',
    poster: '/posters/terrace_sundowner_jam.jpg',
    videoUrl: 'https://pub-1802bb19214743ffa99aa227f25e7ede.r2.dev/heroSec/HerSec%20Videos/farm%20house%20Portrait.mp4',
    videoTitle: 'Rooftop Sundowner Jam Session',
    regularPrice: '₹20,000',
    offerPrice: '₹8,499',
    discount: 'Flat 58% OFF',
    slots: '4 Slots Left for Weekend',
    rating: '4.94★ (680+ Rooftops)'
  },
  {
    id: 'birthday-party',
    category: 'Birthday Celebrations',
    tab: '🎂 Birthday Bash',
    tag: '🎉 BIRTHDAY SPECIAL',
    title: 'Birthday House Party Singer',
    subtitle: 'High-Energy Bollywood Medleys, Retro Classics & Singalongs with Portable Sound',
    poster: '/posters/birthday_party_singer.jpg',
    videoUrl: 'https://pub-1802bb19214743ffa99aa227f25e7ede.r2.dev/heroSec/HerSec%20Videos/Birthday%20Party%20Landscape.mp4',
    videoTitle: 'Birthday Celebration Live Performance',
    regularPrice: '₹15,000',
    offerPrice: '₹6,499',
    discount: 'Flat 57% OFF',
    slots: '5 Slots Left Today',
    rating: '4.98★ (2,100+ Birthdays)'
  },
  {
    id: 'farmhouse-cocktail',
    category: 'Farmhouse & Cocktails',
    tab: '🍸 Farmhouse Party',
    tag: '🌴 LUXURY LAWN PARTY',
    title: 'Farmhouse Lawn Cocktail Party',
    subtitle: 'Bollywood Fusion Singer & Saxophone Duo for Poolside & Lawn Gatherings',
    poster: '/posters/farmhouse_cocktail_party.jpg',
    videoUrl: 'https://pub-1802bb19214743ffa99aa227f25e7ede.r2.dev/heroSec/HerSec%20Videos/farm%20house%20Portrait.mp4',
    videoTitle: 'Farmhouse Cocktail Night Performance',
    regularPrice: '₹32,000',
    offerPrice: '₹13,999',
    discount: 'Flat 56% OFF',
    slots: '2 Slots Left This Weekend',
    rating: '4.97★ (520+ Farmhouses)'
  },
  {
    id: 'ghazal-sufi',
    category: 'Ghazal & Sufi',
    tab: '🌙 Sufi & Ghazal',
    tag: '🕯️ ROMANTIC EVENING',
    title: 'Intimate Ghazal & Sufi Mehfil',
    subtitle: 'Live Harmonium, Acoustic Tabla & Classical Vocalist for Candlelight Dinners & Anniversaries',
    poster: '/posters/ghazal_sufi_night.jpg',
    videoUrl: null,
    videoTitle: null,
    mediaType: 'image',
    regularPrice: '₹24,000',
    offerPrice: '₹9,999',
    discount: 'Flat 58% OFF',
    slots: '3 Slots Left',
    rating: '5.0★ (740+ Anniversaries)'
  },
  {
    id: 'wedding-band',
    category: 'Wedding & Sangeet',
    tab: '👑 Wedding Band',
    tag: '👑 ROYAL SANGEET SPECIAL',
    title: 'Grand Sangeet & Royal Live Bands',
    subtitle: 'High-Octane 5 to 7 Piece Live Troupe, Sufi Rock & Bollywood Anthems',
    poster: '/posters/wedding_sangeet_band.jpg',
    videoUrl: null,
    videoTitle: null,
    mediaType: 'image',
    regularPrice: '₹65,000',
    offerPrice: '₹28,999',
    discount: 'Up to 60% OFF',
    slots: '2 Slots Left for Season',
    rating: '4.98★ (850+ Weddings)'
  },
  {
    id: 'haldi-mehendi',
    category: 'Haldi & Mehendi',
    tab: '🌼 Haldi & Mehendi',
    tag: '💛 WEDDING FESTIVITIES',
    title: 'Haldi & Mehendi Folk & Dholak Troupe',
    subtitle: 'Upbeat Punjabi Wedding Folk, Dholak & Traditional Tappe Singalongs for Home Functions',
    poster: '/posters/haldi_mehendi_celebration.jpg',
    videoUrl: null,
    videoTitle: null,
    mediaType: 'image',
    regularPrice: '₹18,000',
    offerPrice: '₹7,499',
    discount: 'Flat 58% OFF',
    slots: '3 Slots Left',
    rating: '4.95★ (1,100+ Functions)'
  },
  {
    id: 'club-dj',
    category: 'DJs & Club Nights',
    tab: '⚡ DJ & Dhol',
    tag: '⚡ HIGH-OCTANE NIGHTS',
    title: 'Club DJs & Live Punjabi Dhol Beats',
    subtitle: 'Commercial EDM, Bollywood Remixes & Live Dhol with Laser Sound Setup',
    poster: '/posters/club_dj_sundowner.jpg',
    videoUrl: null,
    videoTitle: null,
    mediaType: 'image',
    regularPrice: '₹28,000',
    offerPrice: '₹11,999',
    discount: 'Flat 57% OFF',
    slots: '4 Slots Left for Weekend',
    rating: '4.93★ (980+ DJ Nights)'
  },
  {
    id: 'corporate-gala',
    category: 'Corporate Events',
    tab: '🌟 VIP Corporate',
    tag: '👔 ELITE CORPORATE GALA',
    title: 'Corporate Summits & Celebrity Hosts',
    subtitle: 'Award Show Anchors, Standup Comedians & Mentalists for Annual Galas',
    poster: '/posters/corporate_gala_anchor.jpg',
    videoUrl: null,
    videoTitle: null,
    mediaType: 'image',
    regularPrice: '₹45,000',
    offerPrice: '₹19,999',
    discount: 'Flat 55% OFF',
    slots: '2 Slots Left This Month',
    rating: '4.96★ (540+ Galas)'
  },
  {
    id: 'bhajan-bhakti',
    category: 'Devotional & Bhajan',
    tab: '🪔 Bhajan Sandhya',
    tag: '🙏 SPIRITUAL CONCERT',
    title: 'Bhakti Sangeet & Bhajan Sandhya at Home',
    subtitle: 'Soulful Krishna, Mata Ki Chowki & Kirtan Vocalists with Dholak & Flute for Home Poojas',
    poster: '/posters/bhajan_bhakti_concert.jpg',
    videoUrl: null,
    videoTitle: null,
    mediaType: 'image',
    regularPrice: '₹16,000',
    offerPrice: '₹6,999',
    discount: 'Flat 56% OFF',
    slots: '3 Slots Left',
    rating: '5.0★ (620+ Poojas)'
  }
];

export const FEATURED_IMAGE_CARDS = [
  {
    id: 'hp-acoustic',
    category: 'HOUSE PARTY ACOUSTIC',
    title: 'Private House Party Acoustic Singer',
    subtitle: 'Guitarist & Soulful Vocalist with Compact Sound Setup',
    price: '₹6,999',
    regularPrice: '₹14,999',
    discount: 'Flat 53% OFF',
    tag: '⚡ Best for Living Rooms',
    rating: '4.9★',
    badge: '100% Acoustic Verified',
    image: '/posters/house_party_acoustic.jpg',
  },
  {
    id: 'wedding-sangeet',
    category: 'WEDDING & SANGEET',
    title: 'Grand Sangeet & Royal Live Bands',
    subtitle: 'High-Energy Bollywood 4-5 Piece Live Wedding Ensemble',
    price: '₹28,999',
    regularPrice: '₹55,000',
    discount: 'Flat 47% OFF',
    tag: '👑 Royal Celebrations',
    rating: '5.0★',
    badge: 'Stage Sound Included',
    image: '/posters/wedding_sangeet_band.jpg',
  },
  {
    id: 'terrace-jam',
    category: 'TERRACE & SUNDOWNER',
    title: 'Rooftop Terrace Sundowner Jam',
    subtitle: 'Golden Hour Indie & Bollywood Pop Singalong Vibe',
    price: '₹8,499',
    regularPrice: '₹18,000',
    discount: 'Flat 52% OFF',
    tag: '🌅 Sunset Favourite',
    rating: '4.95★',
    badge: 'Warm Mood Lighting Ready',
    image: '/posters/terrace_sundowner_jam.jpg',
  },
  {
    id: 'birthday-singer',
    category: 'BIRTHDAY CELEBRATIONS',
    title: 'Birthday Party Singer & Live Guitarist',
    subtitle: 'High-Energy Bollywood Medleys & Singalongs with Sound Setup',
    price: '₹6,499',
    regularPrice: '₹15,000',
    discount: 'Flat 57% OFF',
    tag: '🎂 Birthday Special',
    rating: '4.98★',
    badge: 'Mic & Acoustic Gear Included',
    image: '/posters/birthday_party_singer.jpg',
  },
  {
    id: 'ghazal-sufi',
    category: 'SUFI & GHAZAL',
    title: 'Intimate Ghazal & Sufi Mehfil',
    subtitle: 'Harmonium, Acoustic Tabla & Classical Vocalist for Anniversaries',
    price: '₹9,999',
    regularPrice: '₹24,000',
    discount: 'Flat 53% OFF',
    tag: '♥ Romantic Mehfil',
    rating: '5.0★',
    badge: 'Harmonium & Live Tabla',
    image: '/posters/ghazal_sufi_night.jpg',
  },
];
